name: cafe_service

services:
  db:
    image: postgres:17-alpine
    env_file:
      - .env_prod
    ports:
      - "5432:5432"
    volumes:
      # ИСПРАВЛЕНО: Имя volume и путь теперь правильные
      - pg_data:/var/lib/postgresql/data
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s # Можно сделать проверку чуть чаще при старте
      timeout: 5s
      retries: 5
    restart: unless-stopped

  web:
    container_name: booking_cafe
    build: .
    env_file:
      - .env_prod
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    # ИСПРАВЛЕНО: Команда теперь простая и не содержит миграций и --reload
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped

volumes:
  pg_data: {}
